* QML-PM

 Accelerating Precision Medicine with Quantum Computing and AI: Exploring the future of Personalized Health Care

Please refer to https://github.com/shaunsingh/QML-PM/blob/main/paper.pdf for the full version of this paper
Please see https://docs.google.com/presentation/d/1q5QH6U0M_EpMArsLx9iSsVV2LGDRYQCJ5wVSVbzw1hU/edit?usp=sharing for a presentation of the paper

# Abstract

The convergence of quantum computing, artificial intelligence, and precision medicine promises to revolutionize health care. Precision medicine methods identify phenotypes of patients with less-common responses to treatment or unique healthcare needs.  AI  leverages sophisticated computation and inference to generate insights, enables the system to reason and learn, and empowers clinician decision-making through augmented intelligence. Quantum-accelerated machine learning could support further breakthroughs in this area and ultimately enable causal inference models for drugs, identifying and explaining relationships among interventions and treatments on the one hand, and outcomes on the other in real-time, to provide the next-best medical action at the individual level.
